experiment_name: "Gaussian_Diffraction_Linear"
device: "cuda"

physics:
  wavelength: 0.0008
  k: 7853.98
  r_max: 20.0
  z_max: 2000.0
  bounds:
    A: [0.1, 1.0]
    w0: [0.5, 2.0]
    f: [500.0, 10000.0]

model:
  branch_dim: 3
  trunk_dim: 2
  latent_dim: 64
  branch_layers: [64,64,64]
  trunk_layers: [64,64]
  fourier_dim: 64
  fourier_scales: [1.0, 2.0, 5.0, 10.0, 20.0, 40.0, 80.0]
  epsilon_curriculum: 0.01

training:
  batch_size_ic: 10   
  batch_size_pde: 10  

  weights:
    ic_loss: 10.0
    pde_loss_divisor: 1000000

  ic_phase:
    iterations: 2
    learning_rate: 0.001
    threshold: 0.02

  zones:
    zone_1:
      limit: 200.0
      step_size: 5.0
      iterations: 2
      max_retries: 3
      first_learning_rate: 0.0005  # <--- C'est lui le point de départ
      target_error: 0.03

    zone_2:
      limit: 1500.0
      step_size: 2.0
      iterations: 2
      max_retries: 3
      first_learning_rate: 0.0005  # <--- C'est lui le point de départ
      use_lbfgs: True 
      target_error: 0.03 # <--- COHERENCE

    zone_3:
      step_size: 5.0
      iterations: 2
      max_retries: 3
      first_learning_rate: 0.0005  # <--- C'est lui le point de départ
      use_lbfgs: True   # <--- ACTIVATION PARTOUT
      target_error: 0.05
